# Generated by Django 4.2.2 on 2024-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
