import json,datetime
src='/opt/data/HeRmEz/projects/_ops/vercel-live-audit-2026-08-12.json'; out='/opt/data/HeRmEz/projects/_ops/vercel-portfolio-audit-2026-08-12.md'
D=json.load(open(src))
real={'fashion-social':'real product/MVP','card-intel-scanner':'functional MVP (live UI; public data/demo defaults)','combatatlas':'product/review candidate','local-meeting-transcriber-frontend':'product candidate','honda-tech-upgrade':'product/review candidate','journal-app':'product/review candidate','musicai':'real product UI; OAuth/data integration requires functional test','faceless-youtube-channel':'product/review candidate','3d-react-web':'legacy product/demo','stock-news-frontend':'legacy product candidate','journal-ai':'stale/duplicate candidate'}
keep={'fashion-social','card-intel-scanner','combatatlas','local-meeting-transcriber-frontend','musicai'}
fix={'fashion-social','3d-react-web','journal-app','honda-tech-upgrade','faceless-youtube-channel','stock-news-frontend'}
lines=['# Vercel Portfolio Audit — 2026-08-12','',f'**Scope:** team `itmeansbigmountains-projects`; {D["project_count"]} projects. Strictly read-only. No Vercel or Git state was changed.','', '## Executive summary','', '- Provider/API: authentication succeeded; all 55 projects were enumerated.', '- Deployment state: 54 latest production deployments `READY`; `3d-react-web` latest is `BLOCKED` even though its current alias and immutable deployment URL both returned HTTP 200.', '- HTTP: every selected primary/configured alias and every latest deployment URL returned HTTP 200. HTTP success does **not** imply product readiness.', '- Protection: no project reported password, SSO, trusted-IP, or bypass configuration in the project API fields inspected.', '- Git linkage: only `fashion-social` and `3d-react-web` are linked to GitHub. The other 53 have no provider-side Git repository link.', '- Environment readiness: only `fashion-social` (17 names) and `musicai` (34 names) have environment variables. Names/presence only are recorded below; values were never requested or displayed.', '- Portfolio shape: many legacy projects share one bulk deployment commit and render thin/static review outputs. Treat them as archive/delete **candidates only**, never delete without explicit confirmation.', '', '## Wornly / fashion-social verification','', '- Canonical requested URL `https://fashion-social-app.vercel.app`: HTTP 200, polished Wornly homepage, no browser console errors.', '- Compatibility alias `https://wornly-two.vercel.app`: HTTP 200 and points to the same current deployment.', '- Latest immutable deployment: `https://fashion-social-qitheqc7g-itmeansbigmountains-projects.vercel.app` — HTTP 200, `READY`.', '- Alias drift: Vercel project target metadata calls `wornly-two.vercel.app` the first production alias, while the alias API also maps `fashion-social-app.vercel.app` to the same deployment. Branding/canonical intent and provider “primary” are therefore not aligned.', '- **Requested commit `73d512eb7889c7e2c81d2baa2d8d2430c5f76e80` is NOT deployed.** Current production SHA is `d36b03eda2b76d4baf373186f2e8051cacdb25c1`; the requested SHA was absent from the 20 newest deployments inspected.', '- End-user review: polished, responsive-looking desktop layout, real product/MVP presentation, products and voting controls visible. `/shop` and `/api/health` both return 404 despite the header “Shop” affordance; this is the main functional/navigation defect. Several product-image panels appeared as gray placeholders in the captured full-page desktop view (likely image-loading/remote-image issue).', '', '## Inventory', '', '| Project | Primary/configured URL | Latest (state / HTTP) | Framework · Git · env | End-user finding | Recommendation |','|---|---|---|---|---|---|']
for p in D['projects']:
 n=p['name']; pri=p['primary_alias']; ph=(p['health']['primary'] or {}).get('status'); lh=(p['health']['latest'] or {}).get('status'); state=p['latest']['state']; sha=(p['latest']['gitCommitSha'] or 'none')[:8]
 git='GitHub '+p['gitRepository'].get('org','')+'/'+p['gitRepository'].get('repo','') if isinstance(p['gitRepository'],dict) else 'unlinked'
 env=f"{len(p['env_names'])} env names" if p['env_names'] else 'no env vars'
 finding=real.get(n,'static/thin review shell candidate; HTTP healthy, product depth not established')
 if n=='fashion-social': rec='FIX/KEEP — deploy requested SHA; repair `/shop`; align canonical alias'
 elif n=='3d-react-web': rec='FIX or ARCHIVE — latest provider state BLOCKED'
 elif n in keep: rec='KEEP; perform deeper functional test before release'
 elif n in fix: rec='FIX/REVIEW; decide if this is an active product'
 elif n=='journal-ai': rec='ARCHIVE candidate (possible duplicate of journal-app)'
 else: rec='ARCHIVE / DELETE-CANDIDATE after owner confirmation'
 lines.append(f"| `{n}` | [https://{pri}](https://{pri}) ({ph}) | [`{p['latest']['url']}`](https://{p['latest']['url']}) ({state}/{lh}, `{sha}`) | {p['framework'] or 'unset'} · {git} · {env} | {finding} | {rec} |")
lines += ['', '## Environment-variable presence (names only)', '']
for p in D['projects']:
 if p['env_names']: lines.append(f"- **{p['name']} ({len(p['env_names'])}):** `"+'`, `'.join(p['env_names'])+'`')
lines += ['', 'All other projects: **no environment variables present** in the project environment API.', '', '## Browser/end-user checks', '', '- **Wornly:** desktop homepage and full-page visual inspection; console clean; `/shop` and `/api/health` 404; compatibility alias checked. Browser viewport service could not be forced to a true mobile width (`resizeTo` remained 1280px), so mobile responsiveness is not claimed as fully verified.', '- **Card Intel Scanner:** desktop homepage and full-page visual inspection; console clean. Cohesive usable MVP UI with camera/search/watchlist controls and public Pokémon data, but default Charizard values and an empty camera frame mean real camera/OCR behavior still needs device testing.', '- **MusicAI:** live HTML confirms a substantive OAuth-based product UI and clear YouTube-first positioning; environment presence is substantial, but OAuth was not invoked because that would cross into user/account interaction.', '- Other sites: homepage HTTP/provider checks were run for every project; important recent/product-like sites were sampled by HTML/title. Most legacy pages provide little server-visible content and share bulk deployment SHAs, supporting “review shell candidate,” not proof of a functioning end-user product.', '', '## Safety and next actions', '', '1. Do not clean up by deletion yet. First confirm the active shortlist and explicitly approve named retirements.', '2. For Wornly, deploy the missing requested commit through the normal Git integration, then re-check both aliases and `/shop`.', '3. Resolve `3d-react-web` BLOCKED state or archive it.', '4. Review the large legacy shell cohort in batches; preserve handoff context before any confirmed deletion.', '', f'Raw machine inventory: `{src}`', 'Collector script: `/opt/data/HeRmEz/projects/_ops/vercel_audit_collect_2026-08-12.py`', '']
open(out,'w').write('\n'.join(lines)); print(out)
